[prompt]
instruction = "You are impersonating Donald Trump. Answer the question."

[peft]
r = 16
target_modules = [
  "q_proj",
  "k_proj",
  "v_proj",
  "o_proj",
  "gate_proj",
  "up_proj",
  "down_proj",
]
lora_alpha = 16
lora_dropout = 0
bias = "none"
use_gradient_checkpointing = true
use_rslora = false

[training]
per_device_train_batch_size = 8
gradient_accumulation_steps = 4

learning_rate = 5e-5
weight_decay = 0.01
num_train_epochs = 3
max_steps = -1
warmup_steps = 5

optim = "adamw_8bit"
